-- 自动生成：herb-export-site 生产 D1 预播种脚本
-- 由 functions/seed-data.js 导出，执行前请确保表尚未存在或容忍 IF NOT EXISTS

CREATE TABLE IF NOT EXISTS admins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT UNIQUE NOT NULL,
  name_zh TEXT NOT NULL,
  name_en TEXT NOT NULL,
  desc_zh TEXT DEFAULT '',
  desc_en TEXT DEFAULT '',
  icon TEXT DEFAULT 'leaf',
  sort_order INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT UNIQUE NOT NULL,
  category_id INTEGER,
  name_zh TEXT NOT NULL,
  name_en TEXT NOT NULL,
  pinyin TEXT DEFAULT '',
  latin_name TEXT DEFAULT '',
  origin_zh TEXT DEFAULT '',
  origin_en TEXT DEFAULT '',
  part_zh TEXT DEFAULT '',
  part_en TEXT DEFAULT '',
  grade_zh TEXT DEFAULT '',
  grade_en TEXT DEFAULT '',
  spec_zh TEXT DEFAULT '',
  spec_en TEXT DEFAULT '',
  moisture TEXT DEFAULT '',
  ash TEXT DEFAULT '',
  package_zh TEXT DEFAULT '',
  package_en TEXT DEFAULT '',
  moq TEXT DEFAULT '',
  price_min REAL DEFAULT 0,
  price_max REAL DEFAULT 0,
  unit TEXT DEFAULT 'kg',
  shelf_life TEXT DEFAULT '',
  storage_zh TEXT DEFAULT '',
  storage_en TEXT DEFAULT '',
  desc_zh TEXT DEFAULT '',
  desc_en TEXT DEFAULT '',
  usage_zh TEXT DEFAULT '',
  usage_en TEXT DEFAULT '',
  certs TEXT DEFAULT '',
  image TEXT DEFAULT '',
  featured INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active',
  sort_order INTEGER DEFAULT 0,
  views INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS inquiries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  product_id INTEGER,
  product_name TEXT DEFAULT '',
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT DEFAULT '',
  company TEXT DEFAULT '',
  country TEXT DEFAULT '',
  quantity TEXT DEFAULT '',
  message TEXT DEFAULT '',
  status TEXT DEFAULT 'new',
  note TEXT DEFAULT '',
  created_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS company (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  name_zh TEXT DEFAULT '', name_en TEXT DEFAULT '',
  intro_zh TEXT DEFAULT '', intro_en TEXT DEFAULT '',
  address_zh TEXT DEFAULT '', address_en TEXT DEFAULT '',
  phone TEXT DEFAULT '', whatsapp TEXT DEFAULT '',
  email TEXT DEFAULT '', website TEXT DEFAULT '',
  worktime_zh TEXT DEFAULT '', worktime_en TEXT DEFAULT '',
  year_founded TEXT DEFAULT '', employees TEXT DEFAULT '',
  factory_area TEXT DEFAULT '', main_market TEXT DEFAULT '',
  annual_output TEXT DEFAULT '',
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS certificates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name_zh TEXT NOT NULL, name_en TEXT NOT NULL,
  issuer_zh TEXT DEFAULT '', issuer_en TEXT DEFAULT '',
  image TEXT DEFAULT '',
  sort_order INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS banners (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title_zh TEXT DEFAULT '', title_en TEXT DEFAULT '',
  subtitle_zh TEXT DEFAULT '', subtitle_en TEXT DEFAULT '',
  image TEXT DEFAULT '',
  sort_order INTEGER DEFAULT 0,
  status INTEGER DEFAULT 1
);
CREATE TABLE IF NOT EXISTS i18n (
  key TEXT PRIMARY KEY,
  value_zh TEXT DEFAULT '',
  value_en TEXT DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_products_cat ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);

-- categories
INSERT INTO categories (slug,name_zh,name_en,desc_zh,desc_en,icon,sort_order) VALUES ('roots-rhizomes','根及根茎类','Roots & Rhizomes','以根或根茎入药，是中药材出口量最大的品类，多用于滋补、活血、清热。','Roots and rhizomes are the largest exported TCM category, widely used for tonifying, blood activation and heat clearing.','root',1);
INSERT INTO categories (slug,name_zh,name_en,desc_zh,desc_en,icon,sort_order) VALUES ('flowers','花类','Flowers','以花蕾或花序入药，多含挥发油与黄酮，用于清热解表、疏肝理气。','Flower buds and inflorescences rich in volatile oils & flavonoids, used to release exterior and regulate qi.','flower',2);
INSERT INTO categories (slug,name_zh,name_en,desc_zh,desc_en,icon,sort_order) VALUES ('fruits-seeds','果实种子类','Fruits & Seeds','以成熟果实或种子入药，常用于消食、润肠、安神。','Mature fruits and seeds used for digestion, moistening intestines and calming the mind.','fruit',3);
INSERT INTO categories (slug,name_zh,name_en,desc_zh,desc_en,icon,sort_order) VALUES ('barks','皮类','Barks','以树皮或根皮入药，多在春秋采收，用于燥湿、温阳、止泻。','Tree or root bark harvested in spring/autumn, used to dry dampness, warm yang and stop diarrhea.','bark',4);
INSERT INTO categories (slug,name_zh,name_en,desc_zh,desc_en,icon,sort_order) VALUES ('whole-herbs','全草类','Whole Herbs','以全草或地上部分入药，富含挥发油，多用于解表化湿。','Whole aerial parts rich in volatile oil, mainly for releasing exterior and resolving dampness.','herb',5);
INSERT INTO categories (slug,name_zh,name_en,desc_zh,desc_en,icon,sort_order) VALUES ('leaves','叶类','Leaves','以叶片入药，多在花期前采收，用于疏散风热、清肺止咳。','Leaves collected before flowering, used to disperse wind-heat and clear the lung.','leaf',6);
INSERT INTO categories (slug,name_zh,name_en,desc_zh,desc_en,icon,sort_order) VALUES ('fungi-others','菌类及其他','Fungi & Others','真菌类及其他特殊来源药材，多用于扶正固本、利水渗湿。','Fungal and other special-source materials for strengthening resistance and draining dampness.','fungi',7);

-- products
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('angelica-sinensis-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'当归','Angelica Sinensis Root','Dang Gui','Radix Angelicae Sinensis','甘肃岷县','Minxian, Gansu','根','Root','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',9.8,16.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','伞形科当归的干燥根，主根粗长、支根少，断面黄白色，油润，香气浓郁。岷县当归挥发油与阿魏酸含量高，为公认道地产区。','Dried root of Angelica sinensis (Oliv.) Diels. Thick taproot with few branches, yellowish-white oily fracture and strong aroma. Minxian origin guarantees high volatile oil and ferulic acid content.','补血活血、调经止痛、润肠通便。用于血虚萎黄、月经不调、虚寒腹痛、肠燥便秘。','Tonifies blood, activates circulation, regulates menstruation and relieves pain. Used for blood deficiency, irregular menstruation, abdominal pain and constipation.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',1,'active',1);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('astragalus-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'黄芪','Astragalus Root','Huang Qi','Radix Astragali','甘肃陇西 / 山西浑源','Longxi Gansu / Hunyuan Shanxi','根','Root','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',6.2,11.8,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','豆科蒙古黄芪或膜荚黄芪的干燥根。条粗直、质硬而韧、断面纤维性强且显粉性，味微甜，嚼之有豆腥味。','Dried root of Astragalus membranaceus (Fisch.) Bge. or A. membranaceus var. mongholicus. Straight thick root, tough texture, fibrous powdery fracture, mildly sweet with beany note.','补气升阳、固表止汗、利水消肿、生津养血。用于气虚乏力、食少便溏、表虚自汗。','Tonifies qi and raises yang, consolidates the exterior, promotes diuresis. Used for qi deficiency fatigue, poor appetite and spontaneous sweating.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',1,'active',2);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('ginseng-root-white-ginseng',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'人参（生晒参）','Ginseng Root (White Ginseng)','Ren Shen','Radix et Rhizoma Ginseng','吉林抚松','Fusong, Jilin','根及根茎','Root & Rhizome','4~6 年生 / 特等','4–6 Years / Premium','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',42,95,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','五加科人参的干燥根及根茎，主根呈纺锤形，表面黄白色，具疏浅断续的粗横纹及明显的纵皱，质较硬，断面粉性。','Dried root and rhizome of Panax ginseng C.A.Mey. Spindle-shaped main root, yellowish-white surface with transverse wrinkles, hard texture and farinaceous fracture.','大补元气、复脉固脱、补脾益肺、生津安神。用于体虚欲脱、脾虚食少、肺虚喘咳、津伤口渴。','Powerfully tonifies primordial qi, benefits spleen and lung, generates fluid and calms the mind. For collapse from severe deficiency, fatigue and dyspnea.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',1,'active',3);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('panax-notoginseng-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'三七','Panax Notoginseng Root','San Qi','Radix et Rhizoma Notoginseng','云南文山','Wenshan, Yunnan','根及根茎','Root & Rhizome','20~120 头','20–120 heads/500g','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',48,125,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','五加科三七的干燥根及根茎。主根呈类圆锥形或圆柱形，表面灰褐色或灰黄色，有断续的纵皱纹及支根痕，体重质坚实，断面灰绿色或黄绿色。','Dried root and rhizome of Panax notoginseng (Burk.) F.H.Chen. Conical or cylindrical, grey-brown surface, hard and heavy, greyish-green fracture.','散瘀止血、消肿定痛。用于咯血、吐血、衄血、便血、崩漏、外伤出血、胸腹刺痛、跌扑肿痛。','Stops bleeding while dispersing blood stasis, reduces swelling and pain. For various bleeding syndromes and traumatic injuries.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',1,'active',4);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('licorice-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'甘草','Licorice Root','Gan Cao','Radix et Rhizoma Glycyrrhizae','内蒙古 / 甘肃','Inner Mongolia / Gansu','根及根茎','Root & Rhizome','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',4.2,8.6,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','豆科甘草、胀果甘草或光果甘草的干燥根及根茎。外皮松紧不一，表面红棕色或灰棕色，质坚实，断面略显纤维性，黄白色，粉性，味甜而特殊。','Dried root and rhizome of Glycyrrhiza uralensis / inflata / glabra. Reddish-brown surface, firm texture, fibrous farinaceous fracture, distinctly sweet taste.','补脾益气、清热解毒、祛痰止咳、缓急止痛、调和诸药。用于脾胃虚弱、倦怠乏力、咳嗽痰多、痈肿疮毒。','Tonifies spleen qi, clears heat and detoxifies, relieves cough, moderates spasm and harmonizes formulas.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',5);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('codonopsis-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'党参','Codonopsis Root','Dang Shen','Radix Codonopsis','山西长治 / 甘肃','Changzhi Shanxi / Gansu','根','Root','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',12.5,22,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','桔梗科党参、素花党参或川党参的干燥根。呈长圆柱形，稍弯曲，表面黄棕色至灰棕色，根头部有多数疣状突起的茎痕及芽，习称"狮子盘头"。','Dried root of Codonopsis pilosula. Long cylindrical, slightly curved, yellowish-brown surface with characteristic "lion head" crown of stem scars.','健脾益肺、养血生津。用于脾肺气虚、食少倦怠、咳嗽虚喘、气血不足、面色萎黄。','Tonifies spleen and lung qi, nourishes blood and generates fluid. For qi deficiency, fatigue, poor appetite and chronic cough.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',6);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('danshen-salvia-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'丹参','Danshen / Salvia Root','Dan Shen','Radix et Rhizoma Salviae Miltiorrhizae','山东 / 四川中江','Shandong / Zhongjiang Sichuan','根及根茎','Root & Rhizome','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',5.4,9.8,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','唇形科丹参的干燥根及根茎。根茎短粗，顶端有时残留茎基；根数条，长圆柱形，略弯曲，表面棕红色或暗棕红色，粗糙，具纵皱纹。','Dried root and rhizome of Salvia miltiorrhiza Bge. Short thick rhizome, several long cylindrical roots, dark reddish-brown wrinkled surface.','活血祛瘀、通经止痛、清心除烦、凉血消痈。用于胸痹心痛、月经不调、经闭痛经、疮疡肿痛。','Activates blood and dispels stasis, regulates menstruation, relieves pain and calms the heart. For chest pain, amenorrhea and dysmenorrhea.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',7);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('gastrodia-rhizome',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'天麻','Gastrodia Rhizome','Tian Ma','Rhizoma Gastrodiae','云南昭通 / 贵州','Zhaotong Yunnan / Guizhou','块茎','Tuber','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',32,68,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','兰科天麻的干燥块茎。呈椭圆形或长条形，略扁，皱缩而稍弯曲，表面黄白色至黄棕色，有纵皱纹及由潜伏芽排列而成的多轮横环纹，习称"芝麻点"。','Dried tuber of Gastrodia elata Bl. Elliptical or elongated, slightly flattened, yellowish-brown with transverse rings.','息风止痉、平抑肝阳、祛风通络。用于小儿惊风、癫痫抽搐、破伤风、头痛眩晕、手足不遂、风湿痹痛。','Extinguishes wind and stops spasm, suppresses liver yang, unblocks collaterals. For convulsions, headache, dizziness and numbness.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',8);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('ophiopogon-tuber',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'麦冬','Ophiopogon Tuber','Mai Dong','Radix Ophiopogonis','四川绵阳 / 浙江慈溪','Mianyang Sichuan / Cixi Zhejiang','块根','Root Tuber','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',15,29,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','百合科麦冬的干燥块根。呈纺锤形，两端略尖，表面黄白色或淡黄色，有细纵纹，质柔韧，断面黄白色，半透明，中柱细小。','Dried root tuber of Ophiopogon japonicus. Spindle-shaped with pointed ends, pale yellow flexible texture, translucent fracture.','养阴生津、润肺清心。用于肺燥干咳、阴虚痨嗽、喉痹咽痛、津伤口渴、内热消渴、心烦失眠。','Nourishes yin, generates fluid, moistens lung and clears heart. For dry cough, thirst and insomnia.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',9);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('coptis-rhizome',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'黄连','Coptis Rhizome','Huang Lian','Rhizoma Coptidis','重庆石柱 / 四川','Shizhu Chongqing / Sichuan','根茎','Rhizome','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',65,118,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','毛茛科黄连、三角叶黄连或云连的干燥根茎，习称"味连""雅连""云连"。多集聚成簇，常弯曲，形如鸡爪，表面灰黄色或黄褐色，粗糙，有不规则结节状隆起。','Dried rhizome of Coptis chinensis Franch. Clustered and curved like chicken feet, grey-yellow rough surface with nodular swellings. Very bitter.','清热燥湿、泻火解毒。用于湿热痞满、呕吐吞酸、泻痢、黄疸、高热神昏、心烦不寐、血热吐衄、目赤、牙痛、痈肿疔疮。','Clears heat, dries dampness, purges fire and detoxifies. For damp-heat diarrhea, jaundice, high fever and skin infections.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',10);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('atractylodes-macrocephala-rhizome',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'白术','Atractylodes Macrocephala Rhizome','Bai Zhu','Rhizoma Atractylodis Macrocephalae','浙江磐安 / 安徽','Pan''an Zhejiang / Anhui','根茎','Rhizome','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',10.5,18.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','菊科白术的干燥根茎。为不规则的肥厚团块，表面灰黄色或灰棕色，有瘤状突起及断续的纵皱和沟纹，质坚硬不易折断，断面不平坦，黄白色至淡棕色。','Dried rhizome of Atractylodes macrocephala Koidz. Irregular thickened mass, greyish-yellow surface with nodular protrusions, hard texture.','健脾益气、燥湿利水、止汗、安胎。用于脾虚食少、腹胀泄泻、痰饮眩悸、水肿、自汗、胎动不安。','Tonifies spleen qi, dries dampness and promotes diuresis, stops sweating and calms the fetus.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',11);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('szechuan-lovage-rhizome',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'川芎','Szechuan Lovage Rhizome','Chuan Xiong','Rhizoma Chuanxiong','四川都江堰','Dujiangyan, Sichuan','根茎','Rhizome','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',7.2,13.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','伞形科川芎的干燥根茎。为不规则结节状拳形团块，表面黄褐色，粗糙皱缩，有多数平行隆起的轮节，质坚实，断面黄白色或灰黄色，散有黄棕色油室。','Dried rhizome of Ligusticum chuanxiong Hort. Irregular nodular fist-like mass, yellowish-brown rough surface with parallel rings.','活血行气、祛风止痛。用于胸胁刺痛、胸痹心痛、月经不调、经闭痛经、头痛、风湿痹痛。','Activates blood and moves qi, dispels wind and relieves pain. For chest pain, menstrual disorders and headache.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',12);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('white-peony-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'白芍','White Peony Root','Bai Shao','Radix Paeoniae Alba','安徽亳州 / 浙江','Bozhou Anhui / Zhejiang','根','Root','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',6,10.8,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','毛茛科芍药的干燥根，经水煮去皮或去皮后再煮、晒干而成。呈圆柱形，平直或稍弯曲，表面类白色或淡棕红色，光洁或有纵皱纹，质坚实，断面较平坦，类白色或微带棕红色。','Dried boiled & peeled root of Paeonia lactiflora Pall. Cylindrical, whitish or pale reddish-brown, hard and heavy with starchy fracture.','养血调经、敛阴止汗、柔肝止痛、平抑肝阳。用于血虚萎黄、月经不调、自汗盗汗、胁痛、腹痛、四肢挛痛、头痛眩晕。','Nourishes blood and regulates menstruation, astringes yin, softens liver and relieves pain.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',13);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('chinese-yam',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'山药','Chinese Yam','Shan Yao','Rhizoma Dioscoreae','河南焦作（怀山药）','Jiaozuo, Henan','根茎','Rhizome','一级 / 选货','Grade A / Selected','毛山药 / 光山药 / 山药片','Raw / Peeled / Slices','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',4.5,8.8,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','薯蓣科薯蓣的干燥根茎，怀山药为四大怀药之一，粉性足、口感绵密，药食两用。','Dried rhizome of Dioscorea opposita Thunb. "Huai山药" is one of the Four Famous Huai Medicines — starchy and mild, both food and medicine.','补脾养胃、生津益肺、补肾涩精。用于脾虚食少、久泻不止、肺虚喘咳、肾虚遗精、带下、尿频、虚热消渴。','Tonifies spleen and stomach, benefits lung and kidney. For chronic diarrhea, cough and frequent urination.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',14);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('platycodon-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'桔梗','Platycodon Root','Jie Geng','Radix Platycodonis','安徽太和 / 山东','Taihe Anhui / Shandong','根','Root','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',11,19,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','桔梗科桔梗的干燥根。呈圆柱形或略呈纺锤形，下部渐细，表面白色或淡黄白色，不去外皮者表面黄棕色至灰棕色，质脆，断面不平坦，形成层环棕色。','Dried root of Platycodon grandiflorum (Jacq.) A.DC. Cylindrical or slightly spindle-shaped, whitish surface, brittle texture.','宣肺、利咽、祛痰、排脓。用于咳嗽痰多、胸闷不畅、咽痛音哑、肺痈吐脓。','Opens up the lung, benefits the throat, expels phlegm and discharges pus. For cough with copious sputum and sore throat.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',15);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('pinellia-rhizome-processed',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'半夏（法半夏）','Pinellia Rhizome (Processed)','Ban Xia','Rhizoma Pinelliae Preparatum','四川 / 湖北','Sichuan / Hubei','块茎','Tuber','一级 / 选货','Grade A / Selected','法半夏 / 姜半夏 / 清半夏','Fa Banxia / Jiang Banxia / Qing Banxia','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',26,46,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','天南星科半夏的干燥块茎，经甘草石灰水或生姜白矾炮制以降低刺激性。呈类球形，表面白色或浅黄色，顶端有凹陷的茎痕，质坚实，断面洁白，富粉性。','Dried tuber of Pinellia ternata (Thunb.) Breit., processed with lime/ginger/alum to reduce irritancy. Spherical, white and starchy.','燥湿化痰、降逆止呕、消痞散结。用于湿痰寒痰、咳喘痰多、痰饮眩悸、风痰眩晕、呕吐反胃、胸脘痞闷。','Dries dampness and resolves phlegm, directs rebellious qi downward to stop vomiting, dissipates nodules.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',16);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('scrophularia-root',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'玄参','Scrophularia Root','Xuan Shen','Radix Scrophulariae','浙江磐安','Pan''an, Zhejiang','根','Root','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',5.2,9.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','玄参科玄参的干燥根。呈类圆柱形，中间略粗或上粗下细，表面灰黄色或灰褐色，有不规则的纵沟、横向皮孔样突起和稀疏的横裂纹；断面黑色，微有光泽。','Dried root of Scrophularia ningpoensis Hemsl. Cylindrical, greyish-brown surface, black shiny fracture.','清热凉血、滋阴降火、解毒散结。用于热入营血、温毒发斑、热病伤阴、津伤便秘、骨蒸劳嗽、目赤、咽痛、瘰疬、痈肿疮毒。','Clears heat and cools blood, nourishes yin and descends fire, detoxifies and dissipates nodules.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',17);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('fo-ti-root-processed',(SELECT id FROM categories WHERE slug='roots-rhizomes'),'何首乌（制）','Fo-Ti Root (Processed)','Zhi He Shou Wu','Radix Polygoni Multiflori Preparata','河南 / 广东','Henan / Guangdong','块根','Root Tuber','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',5.8,9.9,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','蓼科何首乌的干燥块根，经黑豆汁拌蒸炮制而成。呈不规则皱缩状的块片，表面黑褐色或棕褐色，凹凸不平，质坚硬，断面角质样，棕褐色或黑色。','Dried root tuber of Polygonum multiflorum Thunb., steamed with black bean juice. Irregular dark brown pieces with horny fracture.','补肝肾、益精血、乌须发、强筋骨、化浊降脂。用于血虚萎黄、眩晕耳鸣、须发早白、腰膝酸软、高脂血症。','Tonifies liver and kidney, nourishes essence and blood, darkens hair and strengthens tendons. Also used for hyperlipidemia.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',18);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('honeysuckle-flower',(SELECT id FROM categories WHERE slug='flowers'),'金银花','Honeysuckle Flower','Jin Yin Hua','Flos Lonicerae Japonicae','河南封丘 / 山东平邑','Fengqiu Henan / Pingyi Shandong','花蕾','Flower Bud','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',21,38,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','忍冬科忍冬的干燥花蕾或带初开的花。呈棒状，上粗下细，略弯曲，表面黄白色或绿白色，贮久色渐深，密被短柔毛，气清香，味淡微苦。','Dried flower bud of Lonicera japonica Thunb. Rod-shaped, yellowish-white to greenish-white, densely pubescent, fragrant and slightly bitter.','清热解毒、疏散风热。用于痈肿疔疮、喉痹、丹毒、热毒血痢、风热感冒、温病发热。','Clears heat and detoxifies, disperses wind-heat. For sore throat, boils, dysentery and wind-heat common cold.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',1,'active',1);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('chrysanthemum-flower',(SELECT id FROM categories WHERE slug='flowers'),'菊花（杭白菊）','Chrysanthemum Flower','Ju Hua','Flos Chrysanthemi','浙江桐乡 / 安徽黄山','Tongxiang Zhejiang / Huangshan Anhui','头状花序','Capitulum','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',12,26,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','菊科菊的干燥头状花序，按产地和加工方法分为亳菊、滁菊、贡菊、杭菊。杭白菊花瓣洁白、花心金黄，气清香，味甘微苦，是出口量最大的花茶类药材。','Dried capitulum of Chrysanthemum morifolium Ramat. White petals with golden center, fragrant and slightly bitter. Most exported herbal tea flower.','散风清热、平肝明目、清热解毒。用于风热感冒、头痛眩晕、目赤肿痛、眼目昏花、疮痈肿毒。','Disperses wind and clears heat, calms the liver and improves vision. For headache, red eyes and blurred vision.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',2);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('safflower',(SELECT id FROM categories WHERE slug='flowers'),'红花','Safflower','Hong Hua','Flos Carthami','新疆 / 云南','Xinjiang / Yunnan','花','Flower','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',32,58,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','菊科红花的干燥花。为不带子房的管状花，长 1~2cm，表面红黄色或红色，花冠筒细长，先端 5 裂，质柔软，气微香，味微苦。','Dried tubular flower of Carthamus tinctorius L. Red or red-yellow, slender corolla tube with 5 lobes, soft texture.','活血通经、散瘀止痛。用于经闭、痛经、恶露不行、癥瘕痞块、胸痹心痛、瘀滞腹痛、跌打损伤、疮疡肿痛。','Activates blood and regulates menstruation, dispels stasis and relieves pain. For amenorrhea, dysmenorrhea and traumatic injuries.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',3);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('magnolia-flower-bud',(SELECT id FROM categories WHERE slug='flowers'),'辛夷','Magnolia Flower Bud','Xin Yi','Flos Magnoliae','河南南召 / 四川','Nanzhao Henan / Sichuan','花蕾','Flower Bud','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',13,22,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','木兰科望春花、玉兰或武当玉兰的干燥花蕾。呈长卵形，似毛笔头，基部常具短梗，苞片外表面密被灰白色或灰绿色茸毛，气芳香，味辛凉而稍苦。','Dried flower bud of Magnolia biondii / denudata / sprengeri. Brush-pen shaped, densely greyish-white tomentose, aromatic and pungent.','散风寒、通鼻窍。用于风寒头痛、鼻塞流涕、鼻鼽、鼻渊。','Disperses wind-cold and unblocks the nasal passages. For nasal congestion, sinusitis and cold-induced headache.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',4);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('goji-berry-wolfberry',(SELECT id FROM categories WHERE slug='fruits-seeds'),'枸杞子','Goji Berry / Wolfberry','Gou Qi Zi','Fructus Lycii','宁夏中宁','Zhongning, Ningxia','果实','Fruit','180/220/280/380 粒/50g','180/220/280/380 pcs per 50g','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',8.5,16,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','茄科宁夏枸杞的干燥成熟果实。呈类纺锤形或椭圆形，表面红色或暗红色，顶端有小凸起状的花柱痕，果皮柔韧皱缩，果肉肉质柔润，种子 20~50 粒，味甜微酸。','Dried ripe fruit of Lycium barbarum L. Spindle-shaped red berries with wrinkled tender pericarp and sweet juicy pulp. Zhongning Ningxia is the authentic origin.','滋补肝肾、益精明目。用于虚劳精亏、腰膝酸痛、眩晕耳鸣、阳痿遗精、内热消渴、血虚萎黄、目昏不明。','Nourishes liver and kidney, benefits essence and improves vision. Widely used as a superfruit in food & beverage.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',1,'active',1);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('schisandra-berry',(SELECT id FROM categories WHERE slug='fruits-seeds'),'五味子','Schisandra Berry','Wu Wei Zi','Fructus Schisandrae Chinensis','辽宁 / 吉林','Liaoning / Jilin','果实','Fruit','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',16,30,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','木兰科五味子的干燥成熟果实，习称"北五味子"。呈不规则的球形或扁球形，表面红色、紫红色或暗红色，皱缩，显油润，果肉柔软，味酸；种子肾形，有光泽。','Dried ripe fruit of Schisandra chinensis (Turcz.) Baill. Irregular red to dark-red wrinkled berries, sour taste, shiny kidney-shaped seeds.','收敛固涩、益气生津、补肾宁心。用于久嗽虚喘、梦遗滑精、遗尿尿频、久泻不止、自汗盗汗、津伤口渴、内热消渴、心悸失眠。','Astringes and consolidates, tonifies qi and generates fluid, calms the heart. For chronic cough, night sweats and insomnia.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',2);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('hawthorn-fruit',(SELECT id FROM categories WHERE slug='fruits-seeds'),'山楂','Hawthorn Fruit','Shan Zha','Fructus Crataegi','山东 / 河北承德','Shandong / Chengde Hebei','果实','Fruit','一级 / 选货','Grade A / Selected','山楂片 / 去核 / 整果','Slices / Pitted / Whole','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',4,7.8,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','蔷薇科山里红或山楂的干燥成熟果实。为圆形片，皱缩不平，外皮红色，具皱纹，有灰白色小斑点，果肉深黄色至浅棕色，气微清香，味酸微甜。','Dried ripe fruit of Crataegus pinnatifida Bge. Red wrinkled slices with pale spots, sour and slightly sweet taste.','消食健胃、行气散瘀、化浊降脂。用于肉食积滞、胃脘胀满、泻痢腹痛、瘀血经闭、产后瘀阻、心腹刺痛、高脂血症。','Promotes digestion, moves qi and dispels blood stasis, lowers lipids. For food retention and hyperlipidemia.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',3);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('cassia-seed',(SELECT id FROM categories WHERE slug='fruits-seeds'),'决明子','Cassia Seed','Jue Ming Zi','Semen Cassiae','安徽 / 广西','Anhui / Guangxi','种子','Seed','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',3.2,6,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','豆科决明或小决明的干燥成熟种子。略呈菱方形或短圆柱形，两端平行倾斜，表面绿棕色或暗棕色，平滑有光泽，质坚硬，不易破碎，气微，味微苦。','Dried ripe seed of Cassia obtusifolia L. or C. tora L. Rhomboid to short cylindrical, glossy greenish-brown, very hard.','清热明目、润肠通便。用于目赤涩痛、羞明多泪、头痛眩晕、目暗不明、大便秘结。','Clears heat and brightens the eyes, moistens intestines to relieve constipation. Popular in slimming teas.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',4);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('coix-seed-job-s-tears',(SELECT id FROM categories WHERE slug='fruits-seeds'),'薏苡仁','Coix Seed (Job''s Tears)','Yi Yi Ren','Semen Coicis','贵州兴仁 / 福建','Xingren Guizhou / Fujian','种仁','Kernel','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',3,5.8,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','禾本科薏苡的干燥成熟种仁。呈宽卵形或长椭圆形，表面乳白色，光滑，偶有残存的黄褐色种皮，一端钝圆，另端较宽而微凹，质坚实，断面白色，粉性。','Dried ripe kernel of Coix lacryma-jobi var. ma-yuen. Milky-white smooth oval kernels, firm and starchy. Both food and medicine.','利水渗湿、健脾止泻、除痹、排脓、解毒散结。用于水肿、脚气、小便不利、脾虚泄泻、湿痹拘挛、肺痈、肠痈。','Promotes diuresis and drains dampness, strengthens spleen to stop diarrhea, discharges pus and dissipates nodules.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',5);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('red-jujube-chinese-date',(SELECT id FROM categories WHERE slug='fruits-seeds'),'大枣（红枣）','Red Jujube / Chinese Date','Da Zao','Fructus Jujubae','新疆若羌 / 河北沧州','Ruoqiang Xinjiang / Cangzhou Hebei','果实','Fruit','一级 / 选货','Grade A / Selected','特级 / 一级 / 去核 / 枣片','Super / Grade A / Pitted / Slices','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',3.5,7.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','鼠李科枣的干燥成熟果实。呈椭圆形或球形，表面暗红色，略带光泽，有不规则皱纹，基部凹陷，有短果梗，外果皮薄，中果皮棕黄色或淡褐色，肉质柔软，富糖性而油润。','Dried ripe fruit of Ziziphus jujuba Mill. Dark red wrinkled berries with soft sugary pulp. Ruoqiang Xinjiang grade is the premium export origin.','补中益气、养血安神。用于脾虚食少、乏力便溏、妇人脏躁、失眠。','Tonifies the middle and benefits qi, nourishes blood and calms the mind. For fatigue, loose stools and insomnia.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',6);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('longan-aril',(SELECT id FROM categories WHERE slug='fruits-seeds'),'龙眼肉（桂圆肉）','Longan Aril','Long Yan Rou','Arillus Longan','广西 / 福建莆田','Guangxi / Putian Fujian','假种皮','Aril','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',10.5,19,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','无患子科龙眼的假种皮，去核去壳后干燥而成。呈纵向破裂的不规则薄片，常数片粘结，棕褐色，半透明，质柔润，气微香，味甜。','Dried aril of Dimocarpus longan Lour. Irregular brown translucent sticky slices, very sweet and aromatic.','补益心脾、养血安神。用于气血不足、心悸怔忡、健忘失眠、血虚萎黄。','Tonifies heart and spleen, nourishes blood and calms the mind. For palpitations, forgetfulness and insomnia.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',7);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('monk-fruit-luo-han-guo',(SELECT id FROM categories WHERE slug='fruits-seeds'),'罗汉果','Monk Fruit / Luo Han Guo','Luo Han Guo','Fructus Siraitiae','广西桂林永福','Yongfu, Guilin, Guangxi','果实','Fruit','一级 / 选货','Grade A / Selected','大果 / 中果 / 小果','Large / Medium / Small','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',26,48,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','葫芦科罗汉果的干燥果实。呈卵形、椭圆形或球形，表面褐色、黄褐色或绿褐色，有深色斑块及黄色柔毛，体轻，质脆，果皮薄，易破，味极甜。罗汉果甜苷是天然零热量甜味剂。','Dried fruit of Siraitia grosvenorii. Oval brownish fruits with yellow pubescence, extremely sweet. Mogroside is a natural zero-calorie sweetener.','清热润肺、利咽开音、滑肠通便。用于肺热燥咳、咽痛失音、肠燥便秘。','Clears heat and moistens the lung, benefits the throat and relieves constipation. Widely used in natural sweetener industry.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',8);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('dried-tangerine-peel',(SELECT id FROM categories WHERE slug='fruits-seeds'),'陈皮','Dried Tangerine Peel','Chen Pi','Pericarpium Citri Reticulatae','广东新会','Xinhui, Guangdong','果皮','Peel','三年陈 / 五年陈 / 十年陈','Aged 3 / 5 / 10 Years','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',7,14.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','芸香科橘及其栽培变种的干燥成熟果皮，采摘成熟果实，剥取果皮，晒干或低温干燥，陈久者良。新会陈皮为广陈皮上品，油室饱满，香气醇厚。','Dried ripe pericarp of Citrus reticulata Blanco, aged for better quality. Xinhui Guangdong is the premium origin with rich oil glands and mellow aroma.','理气健脾、燥湿化痰。用于脘腹胀满、食少吐泻、咳嗽痰多。','Regulates qi and strengthens the spleen, dries dampness and resolves phlegm. For abdominal distension and productive cough.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',9);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('amomum-fruit',(SELECT id FROM categories WHERE slug='fruits-seeds'),'砂仁','Amomum Fruit','Sha Ren','Fructus Amomi','广东阳春 / 云南','Yangchun Guangdong / Yunnan','果实','Fruit','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',46,82,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','姜科阳春砂、绿壳砂或海南砂的干燥成熟果实。呈椭圆形或卵圆形，有不明显的三棱，表面棕褐色，密生刺状突起，果皮薄而软，种子集结成团，气芳香而浓烈，味辛凉微苦。','Dried ripe fruit of Amomum villosum Lour. Oval with three vague ridges, densely spiny brown surface, strongly aromatic.','化湿开胃、温脾止泻、理气安胎。用于湿浊中阻、脘痞不饥、脾胃虚寒、呕吐泄泻、妊娠恶阻、胎动不安。','Transforms dampness and improves appetite, warms the spleen to stop diarrhea, calms the fetus.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',10);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('star-anise',(SELECT id FROM categories WHERE slug='fruits-seeds'),'八角茴香','Star Anise','Ba Jiao Hui Xiang','Fructus Anisi Stellati','广西梧州 / 云南','Wuzhou Guangxi / Yunnan','果实','Fruit','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',8.5,15.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','木兰科八角茴香的干燥成熟聚合果。为聚合果，多由 8 个蓇葖果组成，放射状排列于中轴上，外表面红棕色，有不规则皱纹，内表面淡棕色，平滑有光泽，气芳香，味辛甜。','Dried ripe fruit of Illicium verum Hook.f. Star-shaped aggregate of usually 8 follicles, reddish-brown, strongly aromatic and sweet-pungent.','温阳散寒、理气止痛。用于寒疝腹痛、肾虚腰痛、胃寒呕吐、脘腹冷痛。也是莽草酸（抗流感药物原料）的重要来源。','Warms yang and dispels cold, regulates qi and relieves pain. Also a key industrial source of shikimic acid.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',11);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('cinnamon-bark',(SELECT id FROM categories WHERE slug='barks'),'肉桂','Cinnamon Bark','Rou Gui','Cortex Cinnamomi','广西 / 广东','Guangxi / Guangdong','树皮','Bark','一级 / 选货','Grade A / Selected','桂皮 / 桂通 / 板桂','Quill / Tube / Slab','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',5.5,10.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','樟科肉桂的干燥树皮。呈槽状或卷筒状，外表面灰棕色，稍粗糙，有不规则的细皱纹及横向突起的皮孔，内表面红棕色，略平坦，有细纵纹，划之显油痕，气香浓烈，味甜辣。','Dried bark of Cinnamomum cassia Presl. Channeled or quilled, grey-brown outside and reddish-brown inside, strongly aromatic, sweet and pungent.','补火助阳、引火归元、散寒止痛、温通经脉。用于阳痿宫冷、腰膝冷痛、肾虚作喘、虚阳上浮、眩晕目赤、心腹冷痛、虚寒吐泻、寒疝腹痛、痛经经闭。','Warms and supplements fire-yang, dispels cold and relieves pain, unblocks the meridians.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',1);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('eucommia-bark',(SELECT id FROM categories WHERE slug='barks'),'杜仲','Eucommia Bark','Du Zhong','Cortex Eucommiae','贵州遵义 / 四川','Zunyi Guizhou / Sichuan','树皮','Bark','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',7,13,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','杜仲科杜仲的干燥树皮。呈板片状或两边稍向内卷，外表面淡棕色或灰褐色，有明显的皱纹或纵裂槽纹，内表面暗紫色，光滑，质脆易折断，断面有细密银白色富弹性的橡胶丝相连。','Dried bark of Eucommia ulmoides Oliv. Flat slabs, grey-brown outside, dark purple inside; breaking reveals silvery elastic rubber threads.','补肝肾、强筋骨、安胎。用于肝肾不足、腰膝酸痛、筋骨无力、头晕目眩、妊娠漏血、胎动不安。','Tonifies liver and kidney, strengthens tendons and bones, calms the fetus. For lower back pain and weakness.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',2);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('magnolia-bark',(SELECT id FROM categories WHERE slug='barks'),'厚朴','Magnolia Bark','Hou Po','Cortex Magnoliae Officinalis','四川 / 湖北恩施','Sichuan / Enshi Hubei','干皮 / 根皮 / 枝皮','Trunk / Root / Branch Bark','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',9,16.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','木兰科厚朴或凹叶厚朴的干燥干皮、根皮及枝皮。干皮呈卷筒状或双卷筒状，外表面灰棕色或灰褐色，粗糙，有时呈鳞片状，较易剥落，内表面紫棕色或深紫褐色，较平滑，具细密纵纹，划之显油痕。','Dried bark of Magnolia officinalis Rehd. et Wils. Quilled, grey-brown rough outside, purple-brown smooth inside. Contains honokiol & magnolol.','燥湿消痰、下气除满。用于湿滞伤中、脘痞吐泻、食积气滞、腹胀便秘、痰饮喘咳。','Dries dampness and dissolves phlegm, descends qi and relieves fullness. Contains magnolol & honokiol, widely researched.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',3);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('phellodendron-bark',(SELECT id FROM categories WHERE slug='barks'),'黄柏','Phellodendron Bark','Huang Bai','Cortex Phellodendri Chinensis','四川 / 吉林','Sichuan / Jilin','树皮','Bark','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',11,19,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','芸香科黄檗（关黄柏）或黄皮树（川黄柏）的干燥树皮。呈板片状或浅槽状，外表面黄褐色或黄棕色，平坦或具纵沟纹，内表面暗黄色或淡棕色，具细密的纵棱纹，体轻，质硬，断面纤维性，呈裂片状分层，深黄色，味极苦。','Dried bark of Phellodendron chinense Schneid. or P. amurense Rupr. Yellow bitter bark, fibrous layered fracture. Rich in berberine.','清热燥湿、泻火除蒸、解毒疗疮。用于湿热泻痢、黄疸尿赤、带下阴痒、热淋涩痛、脚气痿躄、骨蒸劳热、盗汗、遗精、疮疡肿毒、湿疹湿疮。','Clears heat and dries dampness, purges fire and relieves steaming bone fever, detoxifies sores. Source of berberine.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',4);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('peppermint-field-mint',(SELECT id FROM categories WHERE slug='whole-herbs'),'薄荷','Peppermint / Field Mint','Bo He','Herba Menthae','江苏南通 / 安徽','Nantong Jiangsu / Anhui','地上部分','Aerial Part','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',5.2,9.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','唇形科薄荷的干燥地上部分。茎呈方柱形，有对生分枝，表面紫棕色或淡绿色，棱角处具茸毛，质脆，断面白色，髓部中空；叶对生，多卷缩破碎，揉搓后有特殊清凉香气，味辛凉。','Dried aerial part of Mentha haplocalyx Briq. Square stems, opposite leaves, strong cooling menthol aroma when crushed.','疏散风热、清利头目、利咽、透疹、疏肝行气。用于风热感冒、风温初起、头痛、目赤、喉痹、口疮、风疹、麻疹、胸胁胀闷。','Disperses wind-heat, clears head and eyes, benefits throat and releases rashes. Also soothes liver qi.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',1);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('houttuynia-herb',(SELECT id FROM categories WHERE slug='whole-herbs'),'鱼腥草','Houttuynia Herb','Yu Xing Cao','Herba Houttuyniae','四川 / 贵州','Sichuan / Guizhou','地上部分','Aerial Part','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',4.2,8,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','三白草科蕺菜的新鲜全草或干燥地上部分。茎呈扁圆柱形，扭曲，表面棕黄色，具纵棱数条，质脆易折断；叶互生，叶片卷折皱缩，展平后呈心形，搓碎有鱼腥气，味微涩。','Dried aerial part of Houttuynia cordata Thunb. Flattened twisted stems, heart-shaped leaves, characteristic fishy odor.','清热解毒、消痈排脓、利尿通淋。用于肺痈吐脓、痰热喘咳、热痢、热淋、痈肿疮毒。','Clears heat and detoxifies, discharges pus and promotes diuresis. For lung abscess, cough and urinary infection.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',2);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('patchouli-herb',(SELECT id FROM categories WHERE slug='whole-herbs'),'广藿香','Patchouli Herb','Guang Huo Xiang','Herba Pogostemonis','广东肇庆 / 海南','Zhaoqing Guangdong / Hainan','地上部分','Aerial Part','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',6.5,12,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','唇形科广藿香的干燥地上部分。茎略呈方柱形，多分枝，枝条稍曲折，表面被柔毛，质脆易折断，断面中部有髓；叶对生，皱缩成团，展平后叶片呈卵形或椭圆形，两面均被灰白色茸毛，气香特异，味微苦。','Dried aerial part of Pogostemon cablin (Blanco) Benth. Square branched stems, tomentose oval leaves, distinctive earthy aroma.','芳香化浊、和中止呕、发表解暑。用于湿浊中阻、脘痞呕吐、暑湿表证、湿温初起、发热倦怠、胸闷不舒、腹痛吐泻。','Aromatically transforms turbid dampness, harmonizes the middle to stop vomiting, releases summer-heat. Also source of patchouli oil.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',3);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('motherwort-herb',(SELECT id FROM categories WHERE slug='whole-herbs'),'益母草','Motherwort Herb','Yi Mu Cao','Herba Leonuri','河南 / 安徽','Henan / Anhui','地上部分','Aerial Part','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',3.8,7.2,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','唇形科益母草的新鲜或干燥地上部分。茎呈方柱形，四面凹下成纵沟，表面灰绿色或黄绿色，体轻质韧，断面中部有白色髓；叶交互对生，多皱缩破碎，完整者下部叶掌状 3 裂，上部叶羽状深裂或浅裂成 3 片。','Dried aerial part of Leonurus japonicus Houtt. Square grooved stems, palmately lobed leaves, used worldwide in women''s health.','活血调经、利尿消肿、清热解毒。用于月经不调、痛经经闭、恶露不尽、水肿尿少、疮疡肿毒。','Activates blood and regulates menstruation, promotes diuresis, clears heat and detoxifies.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',4);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('mugwort-ai-ye',(SELECT id FROM categories WHERE slug='leaves'),'艾叶','Mugwort / Ai Ye','Ai Ye','Folium Artemisiae Argyi','湖北蕲春 / 河南南阳','Qichun Hubei / Nanyang Henan','叶','Leaf','一级 / 选货','Grade A / Selected','艾叶 / 艾绒 / 艾条','Leaf / Moxa Wool / Moxa Stick','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',4.5,8.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','菊科艾的干燥叶。多皱缩、破碎，有短柄；完整叶片展平后呈卵状椭圆形，羽状深裂，上表面灰绿色或深黄绿色，有稀疏的柔毛及腺点，下表面密生灰白色绒毛，质柔软，气清香，味苦。','Dried leaf of Artemisia argyi Lev. et Vant. Pinnately lobed leaves, grey-white tomentose beneath, aromatic and bitter. Widely used for moxibustion.','温经止血、散寒止痛、外用祛湿止痒。用于吐血、衄血、崩漏、月经过多、胎漏下血、少腹冷痛、经寒不调、宫冷不孕；外治皮肤瘙痒。','Warms the meridians to stop bleeding, dispels cold and relieves pain; externally relieves itching. Main material for moxibustion.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',1);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('mulberry-leaf',(SELECT id FROM categories WHERE slug='leaves'),'桑叶','Mulberry Leaf','Sang Ye','Folium Mori','浙江 / 四川','Zhejiang / Sichuan','叶','Leaf','一级 / 选货','Grade A / Selected','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',4,7.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','桑科桑的干燥叶，初霜后采收者质佳，习称"霜桑叶"。多皱缩破碎，完整者有柄，叶片展平后呈卵形或宽卵形，上表面黄绿色或浅黄棕色，下表面颜色稍浅，叶脉突出，质脆，气微，味淡微苦涩。','Dried leaf of Morus alba L., best harvested after first frost ("Shuang Sang Ye"). Oval brittle leaves with prominent veins.','疏散风热、清肺润燥、清肝明目。用于风热感冒、肺热燥咳、头晕头痛、目赤昏花。','Disperses wind-heat, clears and moistens the lung, clears liver and improves vision. Popular in herbal tea blends.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',2);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('loquat-leaf',(SELECT id FROM categories WHERE slug='leaves'),'枇杷叶','Loquat Leaf','Pi Pa Ye','Folium Eriobotryae','福建 / 浙江','Fujian / Zhejiang','叶','Leaf','一级 / 选货','Grade A / Selected','净叶 / 蜜炙 / 去毛','Raw / Honey-fried / Defuzzed','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',5,9,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','蔷薇科枇杷的干燥叶。呈长圆形或倒卵形，先端尖，基部楔形，边缘有疏锯齿，近基部全缘，上表面灰绿色、黄棕色或红棕色，较光滑，下表面密被黄色绒毛，主脉显著突起，质脆，味微苦。','Dried leaf of Eriobotrya japonica (Thunb.) Lindl. Oblong leaves with serrated margins, yellow tomentose underside.','清肺止咳、降逆止呕。用于肺热咳嗽、气逆喘急、胃热呕逆、烦热口渴。','Clears the lung and stops cough, directs rebellious qi downward to stop vomiting.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',3);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('reishi-lingzhi-mushroom',(SELECT id FROM categories WHERE slug='fungi-others'),'灵芝（赤芝）','Reishi / Lingzhi Mushroom','Ling Zhi','Ganoderma Lucidum','浙江龙泉 / 福建武夷山','Longquan Zhejiang / Wuyishan Fujian','子实体','Fruiting Body','一级 / 选货','Grade A / Selected','整芝 / 切片 / 孢子粉 / 提取物','Whole / Sliced / Spore Powder / Extract','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',22,48,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','多孔菌科真菌赤芝或紫芝的干燥子实体。菌盖木栓质，肾形、半圆形或近圆形，皮壳坚硬，黄褐色至红褐色，有光泽，具环状棱纹和辐射状皱纹，菌肉白色至淡棕色，味苦。','Dried fruiting body of Ganoderma lucidum (Curtis) P.Karst. Kidney-shaped woody cap, reddish-brown and glossy with concentric rings.','补气安神、止咳平喘。用于心神不宁、失眠心悸、肺虚咳喘、虚劳短气、不思饮食。','Tonifies qi and calms the spirit, relieves cough and asthma. Popular worldwide as an adaptogen.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',1,'active',1);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('poria-fu-ling',(SELECT id FROM categories WHERE slug='fungi-others'),'茯苓','Poria / Fu Ling','Fu Ling','Poria cocos','云南 / 湖北罗田','Yunnan / Luotian Hubei','菌核','Sclerotium','一级 / 选货','Grade A / Selected','白茯苓丁 / 茯苓块 / 茯苓皮 / 茯神','White Cubes / Blocks / Peel / Fu Shen','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','200 kg',6.5,11.5,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','多孔菌科真菌茯苓的干燥菌核，多寄生于马尾松或赤松的根上。呈类球形、椭圆形、扁圆形或不规则团块，外皮薄而粗糙，棕褐色至黑褐色，有明显的皱缩纹理，体重质坚实，断面颗粒性，白色或淡红色，粘牙。','Dried sclerotium of Poria cocos (Schw.) Wolf, parasitic on pine roots. Firm globular mass, brown rough outer skin, white granular fracture.','利水渗湿、健脾、宁心。用于水肿尿少、痰饮眩悸、脾虚食少、便溏泄泻、心神不安、惊悸失眠。','Promotes diuresis and drains dampness, strengthens the spleen and calms the mind.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',2);
INSERT INTO products (slug,category_id,name_zh,name_en,pinyin,latin_name,origin_zh,origin_en,part_zh,part_en,grade_zh,grade_en,spec_zh,spec_en,moisture,ash,package_zh,package_en,moq,price_min,price_max,unit,shelf_life,storage_zh,storage_en,desc_zh,desc_en,usage_zh,usage_en,certs,featured,status,sort_order) VALUES ('cordyceps-sinensis',(SELECT id FROM categories WHERE slug='fungi-others'),'冬虫夏草','Cordyceps Sinensis','Dong Chong Xia Cao','Cordyceps sinensis','青海玉树 / 西藏那曲','Yushu Qinghai / Nagqu Tibet','复合体','Complex (fungus + larva)','2000/3000/4000 条/kg','2000/3000/4000 pcs per kg','整枝 / 切片 / 粉末','Whole / Sliced / Powder','≤ 13%','≤ 7%','25kg/袋（编织袋或纸箱，可定制）','25kg/bag (woven bag or carton, customizable)','100 g',18000,32000,'kg','24 个月 / 24 months','置阴凉干燥处，密封，防蛀防潮','Store in a cool dry place, sealed, protect from moisture & insects','麦角菌科真菌冬虫夏草菌寄生在蝙蝠蛾科昆虫幼虫上的子座和幼虫尸体的干燥复合体。虫体似蚕，表面深黄色至黄棕色，有环纹 20~30 个，足 8 对；子座细长圆柱形，表面深棕色至棕褐色，气微腥，味微苦。需提供濒危物种进出口许可文件。','Dried complex of the fungus Cordyceps sinensis and its host larva. Caterpillar-shaped body with a slender stem-like stroma. CITES documentation required for export.','补肾益肺、止血化痰。用于肾虚精亏、阳痿遗精、腰膝酸痛、久咳虚喘、劳嗽痰血。','Tonifies kidney and lung, stops bleeding and resolves phlegm. For impotence, chronic cough and lower back pain.','GMP, ISO9001, HACCP, COA, Phytosanitary Certificate',0,'active',3);

-- company
INSERT INTO company (id,name_zh,name_en,intro_zh,intro_en,address_zh,address_en,phone,whatsapp,email,website,worktime_zh,worktime_en,year_founded,employees,factory_area,main_market,annual_output) VALUES (1,'华源堂中药材进出口有限公司','Huayuan Tang Chinese Herbs Import & Export Co., Ltd.','公司始创于 1993 年，总部位于中国药都安徽亳州，是集种植基地、饮片加工、质量检测与国际贸易于一体的中药材专业供应商。我们在甘肃、云南、宁夏、四川、广西等道地产区建有 12 个合作种植基地与 3 个现代化加工车间，年加工能力逾 8,000 吨。产品远销欧盟、美国、日本、韩国、东南亚及中东等 40 多个国家和地区，长期为保健品、功能食品、草本茶、化妆品及制药企业提供稳定的原料供应与 OEM/ODM 服务。','Founded in 1993 and headquartered in Bozhou (China''s herb capital), we are a professional supplier integrating planting bases, decoction-piece processing, quality testing and international trade. We operate 12 partner farms and 3 modern processing workshops across authentic producing regions including Gansu, Yunnan, Ningxia, Sichuan and Guangxi, with over 8,000 tons annual capacity. Our products are exported to 40+ countries and regions in the EU, US, Japan, Korea, Southeast Asia and the Middle East, serving nutraceutical, functional food, herbal tea, cosmetic and pharmaceutical manufacturers with stable supply and OEM/ODM services.','安徽省亳州市谯城区药材交易中心 A 区 18 号','No.18, Block A, Herb Trading Center, Qiaocheng District, Bozhou, Anhui, China','+86-558-8888-6688','+86-138-0567-8888','export@huayuantang-herb.com','www.huayuantang-herb.com','周一至周六 8:30–18:00（GMT+8）','Mon–Sat 8:30–18:00 (GMT+8)','1993','260+','32,000 m²','欧盟 / 美国 / 日韩 / 东南亚 / 中东（40+ 国家）','8,000 吨 / 年');

-- certificates
INSERT INTO certificates (name_zh,name_en,issuer_zh,issuer_en,sort_order) VALUES ('GMP 药品生产质量管理规范','GMP (Good Manufacturing Practice)','国家药品监督管理局','NMPA',1);
INSERT INTO certificates (name_zh,name_en,issuer_zh,issuer_en,sort_order) VALUES ('ISO 9001 质量管理体系','ISO 9001 Quality Management System','SGS 通标标准技术服务','SGS',2);
INSERT INTO certificates (name_zh,name_en,issuer_zh,issuer_en,sort_order) VALUES ('HACCP 食品安全管理体系','HACCP Food Safety System','SGS 通标标准技术服务','SGS',3);
INSERT INTO certificates (name_zh,name_en,issuer_zh,issuer_en,sort_order) VALUES ('有机产品认证（EU / NOP）','Organic Certification (EU / NOP)','ECOCERT 国际有机认证中心','ECOCERT',4);
INSERT INTO certificates (name_zh,name_en,issuer_zh,issuer_en,sort_order) VALUES ('出口食品生产企业备案','Export Food Production Enterprise Registration','中华人民共和国海关','China Customs',5);
INSERT INTO certificates (name_zh,name_en,issuer_zh,issuer_en,sort_order) VALUES ('原产地证明 / 植检证书','Certificate of Origin / Phytosanitary Certificate','中国国际贸易促进委员会','CCPIT',6);

-- banners
INSERT INTO banners (title_zh,title_en,subtitle_zh,subtitle_en,sort_order) VALUES ('道地药材 · 全球直供','Authentic Herbs · Global Supply','12 个道地产区基地 · 8,000 吨年产能 · 40+ 国家长期供货','12 origin bases · 8,000 t annual capacity · Exporting to 40+ countries',1);
INSERT INTO banners (title_zh,title_en,subtitle_zh,subtitle_en,sort_order) VALUES ('每批次 COA 检测报告','COA for Every Batch','水分 · 灰分 · 农残 · 重金属 · 黄曲霉毒素 全项检测','Moisture · Ash · Pesticide · Heavy metals · Aflatoxin — fully tested',2);
INSERT INTO banners (title_zh,title_en,subtitle_zh,subtitle_en,sort_order) VALUES ('免费样品 · 7 天寄达','Free Samples · Shipped in 7 Days','支持小批量试单，整柜拼柜均可，FOB / CIF / EXW 灵活条款','Small trial orders welcome, FCL & LCL, FOB / CIF / EXW terms',3);

-- admin (admin / admin123)
INSERT INTO admins (username,password_hash,salt) VALUES ('admin','c90204e5db908b3526ca70015ba57bfc4d57e1139153149a57921c8cf162fb67f6a8857ea63b25a70ed753bdd23cb424b9a220852dacebb2b798fbece2b5c7f2','246bed4b68c2cd55da8a5eda184ea0b1');
